### ISSUE TITLE
Fix Library.html with web components

### ISSUE THREAD

**Issue by Zeyddd** [CSE-110-Group-13/cse110-sp24-group13#37]

**Comment by aleyu0** [comment]
i have added components to the library, as well as adapted the js to allow sort (need to test). Also styled the page. 

![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/e22d769d-1083-4509-bb94-5e7091e2cae4)

**Comment by aleyu0** [comment]
![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/e6b8aaa1-ce23-4085-b45b-65d5f72bc44f)
