### ISSUE TITLE
Fix the styling of the overview container in homepage and favorites

### ISSUE THREAD

**Issue by MaximPodgore** [CSE-110-Group-13/cse110-sp24-group13#90]
Make it look nice

**Comment by aleyu0** [comment]
objective changed to make the containers responsive to window size

**Comment by aleyu0** [comment]
overview styling for home and fav fixed. also responsive to window size changes - progress bar hides when in mobile scale. 
text for when there is no project updated slightly and styled

**Comment by aleyu0** [comment]
![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/ddfaba0e-1c72-474e-996d-fb73bee80028)
![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/0e321eef-fb72-40f7-94b5-40309446dd22)
![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/f19da35e-3370-4cee-aceb-aa759d3b64c5)



![Image](https://github.com/CSE-110-Group-13/cse110-sp24-group13/assets/83614302/8105757b-7956-4839-b649-b5ca581fb06d)

**Comment by aleyu0** [comment]
#147
